a

diff --git a/.github/workflows/ollama_review.yml.yaml b/.github/workflows/ollama_review.yml.yaml
--- a/.github/workflows/ollama_review.yml.yaml
+++ b/.github/workflows/ollama_review.yml.yaml
@@ -39,22 +39,14 @@ jobs:
         run: |
           for file in ${{ steps.get-modified-files.outputs.all_changed_files }}; do
           echo $file
-          content=$(git diff origin/main -- "$file" || echo "Failed to get diff for $file")
+          # content=$(git diff origin/main -- "$file" || echo "Failed to get diff for $file")
           # content=$(echo "$content" | sed '/^diff --git/d; /^index /d; /^--- /d; /^\+\+\+ /d; /^@@ /d')
+          content=$(cat "$file")
           content=${content//\'/\'\'}
           content=${content//\"/\\\"}
           content=$(echo "$content" | tr '\n' ' ')
           echo $content
-          json_payload=$(cat <<EOF
-          {
-            "model": "llama3.2",
-            "prompt": "As a software engineer, please review the following code, provide suggestions for improvement, coding best practices, improve readability, and maintainability.:\n\n\`\`\`\n$content\n\`\`\`",
-            "stream": false
-          }
-          EOF
-          )
-          review=$(curl -s http://127.0.0.1:11434/api/generate -d "$json_payload" | jq -r '.response')
-          # review=$(curl -s http://127.0.0.1:11434/api/generate -d '{"model": "llama3.2", "prompt": "As a software engineer, please review the following code, provide suggestions for improvement, coding best practices, improve readability, and maintainability.:${content}", "stream": false}' | jq -r '.response')
+          review=$(curl -s http://127.0.0.1:11434/api/generate -d '{"model": "llama3.2", "prompt": "As a software engineer, please review the following code, provide suggestions for improvement, coding best practices, improve readability, and maintainability.:\n\n```\n'"${content}"'\n```", "stream": false}' | jq -r '.response')
           echo $review
           if [[ $review == "null" ]]
           then
